default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST") { Rails.root.join("tmp/sockets").to_s } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: javika_development

test:
  <<: *default
  database: javika_test

production:
  <<: *default
  database: javika_production
